### ISSUE TITLE
No ParFile converter in YakuzaCommon

### ISSUE THREAD

**Issue by SutandoTsukai181** [Kaplas80/TF3.YakuzaPlugins#10]
When adding an asset that is contained inside a PAR to a script, the `TF3.YarhlPlugin.YakuzaCommon.Converters.Sllz.Compress` Writer is needed. Otherwise, the BinaryFormat won't be converted to ParFile, and the Par writer will throw an unhandled exception when trying to use the file.

There is currently no way of converting a BinaryFormat to ParFile without compressing.

### Suggestion
Add a ParFile converter from BinaryFormat, or allow passing `CompressionType` = 0 to the CompressorParameters, which would skip compression and return the ParFile format.

***

Likewise, `TF3.YarhlPlugin.YakuzaCommon.Converters.Sllz.Decompress` cannot be used as a reader for an asset if the asset does not have SLLZ compression. This is expected, but it causes issues when assets do not consistently have/lack compression, which requires manually checking each asset file to see if it has compression (inside the PAR) or not.

### Suggestion:
Add a `ReaderParameters` class to be used with `Converters.Par.Reader` with an option to automatically decompress files if the ParFileInfo has the compression flag.

If these suggestions are accepted, I can make a PR for them.

**Comment by Kaplas80** [comment]
Of course, fell free to open a PR. All collaboration and improvements are welcomed! 😄

**Comment by SutandoTsukai181** [comment]
Great, I'll start working on it soon.
