### ISSUE TITLE
Sllz.CompressStandard might produce output that cannot be decompressed with ParTool

### ISSUE THREAD

**Issue by SutandoTsukai181** [Kaplas80/TF3.YakuzaPlugins#11]
**Describe the bug**
`YakuzaCommon.Converters.Sllz.CompressStandard` always sets the [first flag to 0x00](https://github.com/Kaplas80/TF3.YakuzaPlugins/blob/main/src/TF3.YarhlPlugin.YakuzaCommon/Converters/Sllz/CompressStandard.cs#L133), where it is sometimes supposed to be different. The resulting par cannot be unpacked with ParTool, and causes the game to crash when loading it.

Note that this does not always happen. Some pars compressed with the same converter do not have this issue.

**To Reproduce**
Par that caused this issue is `wdr_par/wdr.par` from Kenzan. The vanilla files were repacked with compression enabled for all of them (in the game script). The `DotRoot` writer parameter was false, to replicate ParTool alternative mode.

When comparing the repacked par with the one repacked by ParTool (with compression enabled), it can be seen that the first byte after the SLLZ header (0x10) is always 0x00, where in the ParTool repacked par it was 0x19. The rest of the compressed bytes were identical, however.

**Exceptions**
Here is the ParTool stack trace when unpacking the par:
```
Extracting /wdr.par/wdr.par/encount/bugeisha00000000.msg...
Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ParLibrary.Sllz.Decompressor.DecompressV1(DataStream inputDataStream, Int32 compressedSize, Int32 decompressedSize)
   at ParLibrary.Sllz.Decompressor.Convert(ParFile source)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Yarhl.FileFormat.ConvertFormat.With[TConv](Object src)
   at Yarhl.FileSystem.Node.TransformWith[TConv]()
   at ParTool.Program.Extract(Node parNode, String outputFolder)
   at ParTool.Program.Extract(Extract opts)
   at CommandLine.ParserResultExtensions.WithNotParsed[T](ParserResult`1 result, Action`1 action)
   at ParTool.Program.Main(String[] args)

```

Additionally, `Sllz.CompressStandard` allows compressing some streams that ParLibrary would not compress. This is probably because an exception would be thrown when compressing with ParTool, [which causes the file to not be compressed](https://github.com/Kaplas80/ParManager/blob/develop/ParLibrary/Sllz/Compressor.cs#L82-L85). With `Sllz.CompressStandard`, those files are compressed regardless (and still have the same issue with the first flag as described above). I am not sure if this would cause any issues, but thought I should mention it.

**Comment by Kaplas80** [comment]
Hello!

About the "first flag issue", could you send me your recompressed `wdr.par` to make some tests with it?

And, about the last paragraph, the original par files have some conditions when the files are not compressed... One of them is that the compressed file size is bigger than the uncompressed one (this may happen if the file is already compressed). I've replicated this condition in Partool and Sllz.CompressStandard with the exceptions thrown while compressing. But there is also other condition: the file won't be compressed if the difference between the original and compressed size is less than 2048 bytes. I put [that condition](https://github.com/Kaplas80/ParManager/blob/e4f29a47cb3707930143e408c2a524e95b7731e8/ParLibrary/Converter/ParArchiveWriter.cs#L248) in ParTool, but not in Sllz.CompressStandard, so it may cause the different behaviour between the 2 tools.

**Comment by SutandoTsukai181** [comment]
Here is the file: [wdr.zip](https://github.com/Kaplas80/TF3.YakuzaPlugins/files/9277420/wdr.zip)

I used the [010 editor template](https://github.com/CapitanRetraso/Yakuza-010-Editor-Templates/blob/main/Common/yakuza_par.bt) to compare between the two files, so I was able to find the flag difference easily.

> I put [that condition](https://github.com/Kaplas80/ParManager/blob/e4f29a47cb3707930143e408c2a524e95b7731e8/ParLibrary/Converter/ParArchiveWriter.cs#L248) in ParTool, but not in Sllz.CompressStandard, so it may cause the different behaviour between the 2 tools.

I see. So it will not cause any issues since the game should be able to read it, right?
