### ISSUE TITLE
new yaml broken

### ISSUE THREAD

**Issue by Giza** [Kaplas80/TF3.YakuzaPlugins#2]
charTableOffset does not work

`Unhandled exception. YamlDotNet.Core.YamlException: (Line: 12, Col: 10, Idx: 390) - (Line: 12, Col: 18, Idx: 398): Expected 'MappingStart', got 'Scalar' (at Line: 12, Col: 10, Idx: 390).
   at YamlDotNet.Core.ParserExtensions.Require[T](IParser parser)`

there is also an error in the file 
`  - typeName: TF3.YarhlPlugin.YakuzaCommon.Converters.Font.FontExtractor`
Font.**Font**Extractor

**Comment by Kaplas80** [comment]
The code is unfinished, it is plenty of errors and it is not meant to be used yet.
