### ISSUE TITLE
Dll missing

### ISSUE THREAD

**Issue by MaybeDaveyy** [Kaplas80/TF3.YakuzaPlugins#22]
The EPPlus.Interfaces.dll file is missing.
![dll](https://user-images.githubusercontent.com/113808740/190880441-e00ffe6e-c282-4d50-8097-cb5311be5bc6.png)

**Comment by Kaplas80** [comment]
The README.md is already updated for the next TF3 release, but I haven't released it yet (I expect to do before the end of the year).

With the current version, you only need `EPPlus.dll`
